name: GemsSorting
version: ${project.version}
main: com.github.gemssorting.GemsSortingPlugin
api-version: "1.20"
description: Sorts items from input chests (Eye of Ender frame) into receiver chests (#name or .group tag frame)
commands:
  gems:
    description: Opens the web editor of the item groups
    usage: /<command> web
    aliases: [gemssorting]
    permission: gemssorting.web
permissions:
  gemssorting.web:
    description: Get a login link for the group editor (operators only)
    default: op
